=== kesor/shanghai-goldsilver/comex/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["tradeDate", "updateTime", "empty", "totals", "monthData"],
  "properties": {
    "tradeDate": {
      "type": "string",
      "pattern": "^\\d{8}$",
      "description": "Trade date in YYYYMMDD format"
    },
    "updateTime": {
      "type": "string",
      "description": "Timestamp of data update"
    },
    "empty": {
      "type": "boolean",
      "description": "Indicates if data is empty"
    },
    "totals": {
      "$ref": "#/definitions/contractData",
      "description": "Aggregate totals across all months"
    },
    "monthData": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/contractData"
      },
      "description": "Array of monthly contract data objects"
    }
  },
  "definitions": {
    "contractData": {
      "type": "object",
      "required": ["month", "monthID", "globex", "openOutcry", "totalVolume", "blockVolume", "efpVol", "efrVol", "eooVol", "efsVol", "subVol", "pntVol", "tasVol", "deliveries", "opnt", "aon", "atClose", "change", "strike", "exercises"],
      "properties": {
        "month": {"type": "string"},
        "monthID": {"type": "string"},
        "globex": {"type": "string"},
        "openOutcry": {"type": "string"},
        "totalVolume": {"type": "string"},
        "blockVolume": {"type": "string"},
        "efpVol": {"type": "string"},
        "efrVol": {"type": "string"},
        "eooVol": {"type": "string"},
        "efsVol": {"type": "string"},
        "subVol": {"type": "string"},
        "pntVol": {"type": "string"},
        "tasVol": {"type": "string"},
        "deliveries": {"type": "string"},
        "opnt": {"type": "string"},
        "aon": {"type": "string"},
        "atClose": {"type": "string"},
        "change": {"type": "string"},
        "strike": {"type": "string"},
        "exercises": {"type": "string"}
      }
    }
  }
}

=== kesor/shanghai-goldsilver/comex/gold/2026-03-13-data.json
{"tradeDate":"20260313","totals":{"month":"-","monthID":"-","globex":"191,605","openOutcry":"0","totalVolume":"195,280","blockVolume":"613","efpVol":"3,062","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"3,675","tasVol":"1,822","deliveries":"0","opnt":"-","aon":"-","atClose":"419,030","change":"-3,918","strike":"-","exercises":"0"},"monthData":[{"month":"MAR 2026","monthID":"MAR-2026-Calls","globex":"479","openOutcry":"0","totalVolume":"479","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"2,865","change":"318","strike":"0","exercises":"0"},{"month":"APR 2026","monthID":"APR-2026-Calls","globex":"156,825","openOutcry":"0","totalVolume":"160,333","blockVolume":"446","efpVol":"3,062","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"3,508","tasVol":"951","deliveries":"0","opnt":"-","aon":"-","atClose":"201,339","change":"-6,020","strike":"0","exercises":"0"},{"month":"MAY 2026","monthID":"MAY-2026-Calls","globex":"707","openOutcry":"0","totalVolume":"707","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"897","change":"-49","strike":"0","exercises":"0"},{"month":"JUN 2026","monthID":"JUN-2026-Calls","globex":"24,357","openOutcry":"0","totalVolume":"24,451","blockVolume":"94","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"94","tasVol":"773","deliveries":"0","opnt":"-","aon":"-","atClose":"142,148","change":"1,660","strike":"0","exercises":"0"},{"month":"JUL 2026","monthID":"JUL-2026-Calls","globex":"425","openOutcry":"0","totalVolume":"425","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"191","change":"2","strike":"0","exercises":"0"},{"month":"AUG 2026","monthID":"AUG-2026-Calls","globex":"5,512","openOutcry":"0","totalVolume":"5,512","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"74","deliveries":"0","opnt":"-","aon":"-","atClose":"50,421","change":"-164","strike":"0","exercises":"0"},{"month":"SEP 2026","monthID":"SEP-2026-Calls","globex":"26","openOutcry":"0","totalVolume":"26","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"59","change":"1","strike":"0","exercises":"0"},{"month":"OCT 2026","monthID":"OCT-2026-Calls","globex":"1,032","openOutcry":"0","totalVolume":"1,032","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"5,432","change":"66","strike":"0","exercises":"0"},{"month":"NOV 2026","monthID":"NOV-2026-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"71","change":"0","strike":"0","exercises":"0"},{"month":"DEC 2026","monthID":"DEC-2026-Calls","globex":"2,007","openOutcry":"0","totalVolume":"2,080","blockVolume":"73","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"73","tasVol":"24","deliveries":"0","opnt":"-","aon":"-","atClose":"14,093","change":"270","strike":"0","exercises":"0"},{"month":"JAN 2027","monthID":"JAN-2027-Calls","globex":"6","openOutcry":"0","totalVolume":"6","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"70","change":"-3","strike":"0","exercises":"0"},{"month":"FEB 2027","monthID":"FEB-2027-Calls","globex":"160","openOutcry":"0","totalVolume":"160","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"328","change":"-15","strike":"0","exercises":"0"},{"month":"MAR 2027","monthID":"MAR-2027-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"4","change":"0","strike":"0","exercises":"0"},{"month":"APR 2027","monthID":"APR-2027-Calls","globex":"43","openOutcry":"0","totalVolume":"43","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"355","change":"5","strike":"0","exercises":"0"},{"month":"MAY 2027","monthID":"MAY-2027-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"2","change":"0","strike":"0","exercises":"0"},{"month":"JUN 2027","monthID":"JUN-2027-Calls","globex":"21","openOutcry":"0","totalVolume":"21","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"210","change":"11","strike":"0","exercises":"0"},{"month":"JUL 2027","monthID":"JUL-2027-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"2","change":"0","strike":"0","exercises":"0"},{"month":"AUG 2027","monthID":"AUG-2027-Calls","globex":"3","openOutcry":"0","totalVolume":"3","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"44","change":"0","strike":"0","exercises":"0"},{"month":"SEP 2027","monthID":"SEP-2027-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"4","change":"0","strike":"0","exercises":"0"},{"month":"OCT 2027","monthID":"OCT-2027-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"15","change":"0","strike":"0","exercises":"0"},{"month":"NOV 2027","monthID":"NOV-2027-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"8","change":"0","strike":"0","exercises":"0"},{"month":"DEC 2027","monthID":"DEC-2027-Calls","globex":"2","openOutcry":"0","totalVolume":"2","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"280","change":"0","strike":"0","exercises":"0"},{"month":"JAN 2028","monthID":"JAN-2028-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"4","change":"0","strike":"0","exercises":"0"},{"month":"FEB 2028","monthID":"FEB-2028-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"6","change":"0","strike":"0","exercises":"0"},{"month":"MAR 2028","monthID":"MAR-2028-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"2","change":"0","strike":"0","exercises":"0"},{"month":"APR 2028","monthID":"APR-2028-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"4","change":"0","strike":"0","exercises":"0"},{"month":"JUN 2028","monthID":"JUN-2028-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"37","change":"0","strike":"0","exercises":"0"},{"month":"DEC 2028","monthID":"DEC-2028-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"79","change":"0","strike":"0","exercises":"0"},{"month":"JUN 2029","monthID":"JUN-2029-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"59","change":"0","strike":"0","exercises":"0"},{"month":"DEC 2029","monthID":"DEC-2029-Calls","globex":"0","openOutcry":"0","totalVolume":"0","blockVolume":"0","efpVol":"0","efrVol":"0","eooVol":"0","efsVol":"0","subVol":"0","pntVol":"0","tasVol":"0","deliveries":"0","opnt":"-","aon":"-","atClose":"1","change":"0","strike":"0","exercises":"0"}],"updateTime":"2026-03-16T19:00:17.000Z","empty":false}
